### ISSUE TITLE
I never got the missing header files errors etc?

### ISSUE THREAD

**Issue by ravuthlong** [nopenoway0/CS149#3]
Hi, i didn't get the error you were getting last time which is weird but those errors were definitely right. There should be error for missing method declarations at the top. I am writing C in Sublime Text and run it through command line. What do you use?

**Comment by nopenoway0** [comment]
I am actually also using Sublime Text and compiling through the command line as well. There should be a file in your directory named Makefile. Make sure, instead of just compiling using gcc, mingw32, etc .., you cd to the corresponding directory and type "make". This will use the commands in the makefile to compile the file. Having the makefile work correctly will allow us to be sure the professor will be able to compile our project.

**Comment by ravuthlong** [comment]
i actually always use the "make makeHW2" command haha.
maybe i'll do just "make" next time.

**Comment by benj-G** [comment]
hmm that's really weird it didn't give you an error... Everything is working now though. I'm also making a sorter that we can specify what to sort e.g. arrival time, priority, etc. It should help with some of the other algorithms

**Comment by ravuthlong** [comment]
Also, if you see something off with my code, feel free to edit it. I am not very familiar with C, especially with the pointers and double pointers...rip

**Comment by benj-G** [comment]
yeah double pointers are ridiculous
